### ISSUE TITLE
Crime Recorder Feature

### ISSUE THREAD

**Issue by Khauthymo** [Custos-Diretriz/custos-mobile#3] opened 2024-10-23 09:40 UTC
- [ ] Implement UI 
- [ ] Implement functionalities
- [ ] Connect Crime recorder to the starknet contract

**Comment by martinvibes** [comment] 2024-10-23 18:21
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
hello @Khauthymo i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
i would simply  read and follow the instructions and make sure it is implemented to pixel perfect 
kindly assign :)

**Comment by NueloSE** [comment] 2024-10-23 19:48
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a frontend developer with experience in using react,  typescript , javascript, writing and connecting smart contract to dapp using cairo programming language and solidity.

### How I plan on tackling this issue
To tackle this, here’s how I would approach it:

- Implement the UI: I would design the user interface using React js. This would include a forms or input fields where users can record details of a crime (like location and description). I'd also add sections for displaying recorded data.

- Implement Functionalities: Next, I would write  TypeScript functions to handle the form submissions and ensure the data is validated before sending it to the backend. I’d also implement a view function to retrieve data from the StarkNet contract and display it.

- Connect Crime Recorder to StarkNet Contract: I would use Starknet.js to interact with the smart contract. This would involve writing functions to store and retrieve crime data. I’d ensure the storeCrimeRecord function is called to save data on-chain, and I’d use getCrimeRecords to fetch the stored data from the contract

**Comment by josephchimebuka** [comment] 2024-10-24 02:06
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

### How I plan on tackling this issue
I will implement the UI and functionalities and connect it to the starknet contract in 2-3 days

**Comment by Benjtalkshow** [comment] 2024-10-24 07:58
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, and Rust. With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To develop the Crime Recorder feature, I will focus on both the user interface (UI) and the underlying functionalities, ensuring seamless integration with the Starknet contract.

First, I will design and implement an intuitive UI that allows users to easily navigate and interact with the Crime Recorder feature. This will include input fields for recording crime details, a submission button, and a display area for recorded entries, all designed for a user-friendly experience.

Next, I will implement the necessary functionalities that will allow users to record crimes effectively. This will involve creating the logic for capturing user input, validating the data, and preparing it for submission to the blockchain.

Finally, I will connect the Crime Recorder to the Starknet contract. This integration will ensure that all recorded crime entries are securely stored on the blockchain, leveraging Starknet's capabilities for enhanced security and transparency.

**Comment by Yunusabdul38** [comment] 2024-10-24 08:06
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have a strong background in software development, with a focus on blockchain technologies and smart contract development. My experience spans across various domains including decentralized applications (dApps), smart contract testing, and blockchain infrastructure.

With proficiency in Cairo (language), I am adept at writing and testing contracts on different blockchain platforms. I have hands-on experience with the StarkNet ecosystem and the Cairo programming language, which allows me to efficiently develop and test complex smart contracts.

Additionally, my experience with automated testing frameworks, version control systems, and continuous integration (CI) pipelines equips me to approach contract testing in a robust and scalable manner. My background in full-stack development, specifically with React and TypeScript, further strengthens my ability to contribute effectively to the frontend of decentralized applications, ensuring seamless integration with smart contracts.

Leveraging this experience, I can thoroughly implement and optimize the Cairo tests for the crime recorder and agreement contracts, ensuring high reliability and security.

### How I plan on tackling this issue
To implement the UI and functionalities, I would start by designing a user-friendly interface that provides clear access to the crime recording features, ensuring a smooth user experience. I would use React and TypeScript to build a modular and scalable frontend.

For the connection to the StarkNet contract, I would integrate the frontend with StarkNet using web3 libraries or StarkNet.js. This would involve establishing communication between the UI and the Cairo contract, allowing users to interact with the contract securely and efficiently. I would ensure proper error handling, transaction feedback, and security measures to guarantee a reliable connection between the UI and the blockchain.

**Comment by aniruddhaaps** [comment] 2024-10-24 08:38
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have experience in web2 and web3 development and want to contribute in open source. 

### How I plan on tackling this issue
I will make a user-friendly UI with the help of React on the recording of crimes including the form to capture location and description. Implement the necessary functionalities concerning validation of data and submitting of forms. Finally, I will integrate this UI with the StarkNet contract using Starknet.js and thus make it possible to interact in a secure and efficient way when storing and retrieving crimes on-chain.

**Comment by Ekene001** [comment] 2024-10-24 09:36
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. Looking forward to making a positive impact and working with the team!

### How I plan on tackling this issue
To complete this task, I will first implement a user-friendly UI that allows users to record and view crime data. The interface will be intuitive and accessible across devices. Next, I will add core functionalities, such as data input, form validation, and real-time updates, ensuring a smooth user experience.

Finally, I will connect the Crime Recorder to the StarkNet contract, enabling secure and efficient data interaction with the blockchain. This will involve writing logic for submitting and retrieving data while handling transaction confirmations. After thorough testing, I’ll integrate the solution and provide documentation for both technical use and user guidance.

**Comment by Ekene001** [comment] 2024-10-24 10:08
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. Looking forward to making a positive impact and working with the team!

### How I plan on tackling this issue
To implement the navigation bar and wallet connection component, I will first design a responsive and user-friendly navigation bar that links to all key sections of the application. It will include a logo for brand identity and maintain a cohesive style with the rest of the app.

Next, I will integrate the wallet connection functionality, allowing users to securely connect their wallets. This will involve detecting wallet availability, handling connection requests, and updating the UI to reflect the connection status. I will also implement error handling and user feedback mechanisms to guide users through any issues.

After thorough testing to ensure everything works seamlessly, I will integrate the solution into the existing codebase and provide documentation for future maintenance and user onboarding.

**Comment by Goodness5** [comment] 2024-10-24 19:21
@NueloSE you can access figma design here in-case you ommited it in the contribution guidelines https://www.figma.com/design/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?node-id=0-1&node-type=canvas&t=SZrQbCkWDo6zOuvO-0

**Comment by Goodness5** [comment] 2024-10-31 08:35
@NueloSE still waiting for your update on this

**Comment by NueloSE** [comment] 2024-10-31 12:39
@Goodness5 currently making progress would make a PR shortly

**Comment by faytey** [comment] 2024-11-01 12:02
Due to the complexity of this issue and short time, i'd be assigning one more contributor to this issue to pair with @NueloSE  and tidy up the integrations and UI before 3rd, who's up for this.

**Comment by Benjtalkshow** [comment] 2024-11-01 12:03
I am up for this ma

> Due to the complexity of this issue and short time, i'd be assigning one more contributor to this issue to pair with @NueloSE and tidy up the integrations and UI before 3rd, who's up for this.

**Comment by 0xdevcollins** [comment] 2024-11-01 12:05
I am up for this

> Due to the complexity of this issue and short time, i'd be assigning one more contributor to this issue to pair with @NueloSE and tidy up the integrations and UI before 3rd, who's up for this.

**Comment by faytey** [comment] 2024-11-01 12:34
> I am up for this ma
> 
> > Due to the complexity of this issue and short time, i'd be assigning one more contributor to this issue to pair with @NueloSE and tidy up the integrations and UI before 3rd, who's up for this.

Go ahead thanks, @NueloSE please sync up with @Benjtalkshow

**Comment by Benjtalkshow** [comment] 2024-11-01 14:10
Hi @NueloSE 
How can I reach you? Your TG handle please.

**Comment by Benjtalkshow** [comment] 2024-11-01 23:21
Hello @faytey 
Is my services no longer needed for this task?

**Comment by faytey** [comment] 2024-11-01 23:32
> Hello @faytey Is my services no longer needed for this task?

yes please, as @NueloSE has completed the tasks, can you help out with this instead

**Comment by Benjtalkshow** [comment] 2024-11-01 23:33
> > Hello @faytey Is my services no longer needed for this task?
> 
> yes please, as @NueloSE has completed the tasks, can you help out with this instead

Which other task do you want me to help out with?

**Closed** 2024-11-02 18:47 UTC
Labels: enhancement, good first issue, ODHack9
